
package com.weixin.wxservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICoreService", targetNamespace = "http://wxservice.shdt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICoreService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendTemplateData")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendTemplateData", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.SendTemplateData")
    @ResponseWrapper(localName = "SendTemplateDataResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.SendTemplateDataResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/SendTemplateDataRequest", output = "http://wxservice.shdt.com/ICoreService/SendTemplateDataResponse")
    public String sendTemplateData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnCustomMessge", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.ReturnCustomMessge")
    @ResponseWrapper(localName = "returnCustomMessgeResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.ReturnCustomMessgeResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/returnCustomMessgeRequest", output = "http://wxservice.shdt.com/ICoreService/returnCustomMessgeResponse")
    public String returnCustomMessge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "templateMessage", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.TemplateMessage")
    @ResponseWrapper(localName = "templateMessageResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.TemplateMessageResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/templateMessageRequest", output = "http://wxservice.shdt.com/ICoreService/templateMessageResponse")
    public String templateMessage(
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTagList", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.GetTagList")
    @ResponseWrapper(localName = "getTagListResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.GetTagListResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/getTagListRequest", output = "http://wxservice.shdt.com/ICoreService/getTagListResponse")
    public String getTagList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserList", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.GetUserList")
    @ResponseWrapper(localName = "getUserListResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.GetUserListResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/getUserListRequest", output = "http://wxservice.shdt.com/ICoreService/getUserListResponse")
    public String getUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnMessge", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.ReturnMessge")
    @ResponseWrapper(localName = "returnMessgeResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.ReturnMessgeResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/returnMessgeRequest", output = "http://wxservice.shdt.com/ICoreService/returnMessgeResponse")
    public String returnMessge(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param tagidflag
     * @param fromUserName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setTags", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.SetTags")
    @ResponseWrapper(localName = "setTagsResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.SetTagsResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/setTagsRequest", output = "http://wxservice.shdt.com/ICoreService/setTagsResponse")
    public String setTags(
        @WebParam(name = "fromUserName", targetNamespace = "")
        String fromUserName,
        @WebParam(name = "tagidflag", targetNamespace = "")
        String tagidflag);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMenu", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.CreateMenu")
    @ResponseWrapper(localName = "createMenuResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.CreateMenuResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/createMenuRequest", output = "http://wxservice.shdt.com/ICoreService/createMenuResponse")
    public String createMenu(
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteMenu", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.DeleteMenu")
    @ResponseWrapper(localName = "deleteMenuResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.DeleteMenuResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/deleteMenuRequest", output = "http://wxservice.shdt.com/ICoreService/deleteMenuResponse")
    public String deleteMenu();

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createKeFu", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.CreateKeFu")
    @ResponseWrapper(localName = "createKeFuResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.CreateKeFuResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/createKeFuRequest", output = "http://wxservice.shdt.com/ICoreService/createKeFuResponse")
    public String createKeFu(
        @WebParam(name = "content", targetNamespace = "")
        String content);

    /**
     * 
     * @param content
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MessageKeFu")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "MessageKeFu", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.MessageKeFu")
    @ResponseWrapper(localName = "MessageKeFuResponse", targetNamespace = "http://wxservice.shdt.com/", className = "com.shdt.wxservice.client.MessageKeFuResponse")
    @Action(input = "http://wxservice.shdt.com/ICoreService/MessageKeFuRequest", output = "http://wxservice.shdt.com/ICoreService/MessageKeFuResponse")
    public String messageKeFu(
        @WebParam(name = "content", targetNamespace = "")
        String content);

}
